---

host_sshd_port: 2234
host_sshd_user: ansible

ssh_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAIMViZa8jce77Ra/Zo+AwpGJbL2gkjjvyD+nT3AHoxi # Lenz
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICjbOSKGEG1qwcNPNMKtXNl+E8JPFAcpFnWvVz1uoEnc # Levin

locale: en_US.UTF-8
editor: vim
timezone: Europe/Berlin



proxy: 
  - {host: emails.eco, key: emails_eco, port: 4001, internal: "{{ hostvars['emails_eco'].ansible_host }}" }
  - {host: termitelab.com, key: termitelab, port: 4002, internal: "{{ hostvars['termitelab'].ansible_host }}" }

