---

- name: Create Caddy User
  user:
    name: ansible_caddy
    group: root 

- name: Install caddy
  apt: 
    name: caddy
    state: present

- name: Move Caddyfile
  copy: 
    src: ./../templates/Caddyfile
    dest: ~/
    owner: ansible_caddy
    group: root

- name: Enable and start caddy
  service:
    name: caddy
    state: restarted
    enabled: yes

- name: Format and Reload Caddy 
  shell: caddy fmt Caddyfile && caddy reload

