---

- name: Create Caddy User
  user:
    name: ansible_caddy
    group: root 

- name: Install caddy
  apt: 
    name: caddy
    state: present

    #- name: Move Caddyfile
    #copy: 
    #src: ./../templates/Caddyfile
    #dest: ~/
    #owner: caddy_user
    #group: root

- name: Enable and start caddy
  service:
    name: caddy
    state: started
    enabled: yes

