---

- name: create ansible user
  user:
    name: "{{ host_sshd_user }}"
    state: present
    groups: root
    append: true
    create_home: true
    shell: /bin/sh

- name: Add sudo rules for ssh user
  template:
    src: 'sudoers.user.j2'
    dest: '/etc/sudoers.d/{{ host_sshd_user }}'
    validate: 'visudo -cf %s'

# Ensure locale de_DE exists. 
- name: setting location
  community.general.locale_gen:
    name: '{{ locale }}'
    state: present
  notify: restart time

# TODO: do i need this ?
# - name: restart timedatectl
#   service:
#     name: timedatectl
#     state: restarted

- name: UFW - Allow SSH connections
  ufw:
    rule: allow
    port: '{{ host_sshd_port }}'
    proto: tcp

- name: UFW - Deny all other incoming traffic by default
  ufw:
    state: enabled
    policy: deny
    direction: incoming


# restart ntp service      
- name: Restart service timedatectl, in all cases
  service:
    name: timedatectl
    state: restarted

# restart crond jobs to match the new timeframe
- name: Restart crond services
  ansible.builtin.cron:
    name: "restart crond"
    special_time: "reboot"
    job: "sudo service cron restart"
