---

- import_tasks: user.yml
- import_tasks: ssh.yml

- name: Install base packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - htop
    - lsof

- name: UFW - Allow SSH connections
  ufw:
    rule: allow
    proto: tcp
    port: 2234

