---

- name: import OS specific tasks
  import_tasks: freebsd.yml
  when: ansible_facts['os_family'] == 'FreeBSD'

- name: import OS specific tasks
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Ubuntu'

- import_tasks: user.yml
- import_tasks: ssh.yml

- name: Install base packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - htop
    - lsof
    - sudo

- import_tasks: user.yml
- import_tasks: ssh.yml
