---

#- name: create storage directory
#  ansible.builtin.file: 
#    path: /vault/data
#    state: directory
#    mode: '0755'
#use package for installs, (see latest for packages -> auto update) -> see system 
#
#
# handler (systemctl statt vault_server.sh)
#   notify:
#    - restart sshd
#   ==> restart vault on config change 
- name: Creating vault user group
  group: 
    name: "{{ vault_group }}"
  become: true

- name: Creating vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "vault nologin User"
    createhome: "no"
    state: present

- name: config file copy
  template:
    src: ../templates/config.hcl
    dest: /
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: import OS specific tasks
  import_tasks: freebsd.yml
  when: ansible_facts['os_family'] == 'FreeBSD'

- name: import OS specific tasks
  import_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
     
  ## TODO: do i need this ?
# - name: start vault
#   service:
#     name: vault => see if right
#     state: started

