---

- name: restart sshd
  service:
    name: ssh
    state: restarted
  when: ansible_facts['os_family'] != 'FreeBSD'

- name: restart sshd 
  service:
    name: sshd
    state: restarted
  when: ansible_facts['os_family'] == 'FreeBSD'

- name: restart syslogd
  service: 
    name: syslogd
    state: restarted
  when: ansible_facts['os_family'] == 'FreeBSD'

- name: restart time
  service: 
    name: timedatectl
    state: restarted
  when: ansible_facts['os_family'] == 'Debian'

- name: restart time
  service: 
    name: "sudo service ntpd restart"
    state: restarted
  when: ansible_facts['os_family'] == 'FreeBSD'

